# Generated by Django 5.1.6 on 2025-02-17 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(default='2000-12-01', verbose_name='время')),
                ('bought_course', models.CharField(max_length=100, verbose_name='оплаченный курс')),
                ('course_cost', models.IntegerField(verbose_name='сумма оплаты')),
                ('payment_method', models.CharField(choices=[('card', 'card'), ('cash', 'cash')], default='card', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
