# Generated by Django 5.1.6 on 2025-02-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_subscribe_is_sub_subscribe_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
