# Generated by Django 5.1.6 on 2025-02-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(default='https://youtube.com/', max_length=250),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(default='https://youtube.com/', max_length=250),
        ),
    ]
