# Generated by Django 5.1.6 on 2025-02-25 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_payment_bought_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='course_bought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
