# Generated by Django 5.1.6 on 2025-02-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_payment_course_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='RUB', max_length=10, verbose_name='валюта'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='статус оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.TextField(blank=True, null=True, verbose_name='id сессии'),
        ),
    ]
