# Generated by Django 5.1.6 on 2025-02-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_payment_currency_payment_is_paid_payment_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='course_cost',
            new_name='amount',
        ),
    ]
