# Generated by Django 5.1.6 on 2025-02-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_rename_course_cost_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(blank=True, default='2000-12-01', null=True, verbose_name='время'),
        ),
    ]
