# Generated by Django 5.1.6 on 2025-02-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_payment_pay_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='session_id',
        ),
    ]
